language: node_js

node_js:
  - "stable"
  - "10.16.3"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - cp config/index.js.sample config/index.js && echo "{}" > config/mongo.json

script:
  - npm test
  - npm run test:cover

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls